apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: qa
spec:
  limits:
  - default:
      cpu: 200m
      memory: 300Mi
    defaultRequest:
      cpu: 100m
      memory: 200Mi
    type: Container