apiVersion: v1
kind: LimitRange
metadata:
  name: min-max
  namespace: prod
spec:
  limits:
  - max:
      memory: 200Mi
      cpu: 200m
    min:
      memory: 100Mi
      cpu: 100m
    type: Container
