apiVersion: v1
kind: Namespace
metadata:
  name: limitrange
  labels:
    name: limitrange
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-cpu-limit-range
  namespace: limitrange
spec:
  limits:
  - default:
      memory: 200m
      cpu: 300Mi
    defaultRequest:
      memory: 150m
      cpu: 200Mi
    type: Container