apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: deploy-reader
rules:
- apiGroups: ["apps"] 
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-deploy
  namespace: default
subjects:
- kind: User
  name: davidv
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deploy-reader
  apiGroup: rbac.authorization.k8s.io