apiVersion: v1
kind: Pod
metadata:
  name: pod-test01
  labels:
    app: front
    env: dev
spec:
  containers:
  - name: container01
    image: nginx:alpine

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-test02
  labels:
    app: backend
    env: dev
spec:
  containers:
  - name: container01
    image: nginx:alpine