apiVersion: v1
kind: Pod
metadata:
  name: pod-test01
spec:
  containers:
  - name: container01
    image: nginx:alpine

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-test02
spec:
  containers:
  - name: container01
    image: nginx:alpine